// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/account.tsx";
import * as $2 from "./routes/app.tsx";
import * as $3 from "./routes/app/[name].tsx";
import * as $4 from "./routes/blog.tsx";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/tests/erc725.tsx";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/account.tsx": $1,
    "./routes/app.tsx": $2,
    "./routes/app/[name].tsx": $3,
    "./routes/blog.tsx": $4,
    "./routes/index.tsx": $5,
    "./routes/tests/erc725.tsx": $6,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
